import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

import * as Styles from "./index.styles";

import ContainersComment from "../containers/Comment";

import ContextCommentProvider from "../context/comment";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Frontend Mentor | Interactive Comment Section</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Styles.Main>
      <ContextCommentProvider>
        <ContainersComment />
      </ContextCommentProvider>
    </Styles.Main>

    <footer className={styles.attribution}>
      Challenge by{" "}
      <a
        href="https://www.frontendmentor.io?ref=challenge"
        rel="noreferrer"
        target="_blank"
      >
        Frontend Mentor
      </a>
      . Coded by <a href="#">Jomar H. Cui</a>.
    </footer>
  </div>
);

export default Home;
